name: cudagrad

type: python

up:
  - python: 3.10.13
  - pip
  - uv_pip:
      requirements:
      - requirements.txt
  - custom:
      name: Install in dev mode
      met?: pip install -e . --no-deps
      meet: "true"


commands:
  format:
    run: ruff format cudagrad tests

  test:
    run: NUMBA_ENABLE_CUDASIM=1 pytest
